### ISSUE TITLE
VUMETER effect raises error

### ISSUE THREAD

**Issue by pete111** [RanzQ/hyperion-audio-effects#23]
Hello, I found out this - when I choose vumeter effect and run it, then I exit it, it raises this error:
Traceback (most recent call last):
  File "/home/pi/hyperionaudio/effects/spectrum_dump.py", line 307, in on_message
    self.callback(magnitudes)
  File "effects/vumeter.py", line 100, in receive_magnitudes
    self.stop()
  File "effects/vumeter.py", line 95, in stop
    self._spectrum.stop()
  File "/home/pi/hyperionaudio/effects/spectrum_dump.py", line 378, in stop
    self.loop_thread.join()
  File "/usr/lib/python2.7/threading.py", line 940, in join
    raise RuntimeError("cannot join current thread")
RuntimeError: cannot join current thread
/usr/lib/python2.7/dist-packages/gi/overrides/GObject.py:536: Warning: /build/glib2.0-5Ukv2U/glib2.0-2.42.1/./gobject/gsignal.c:2579: instance '0xb55c2d48' has no handler with id '1'
  return func(*args, **kwargs)

(python:1636): GStreamer-CRITICAL **: Bus bus2 has no signal watches attached

**Comment by RanzQ** [comment]
I'll check this at some point.
